apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mongo.name }}
  labels:
    app: {{ .Values.mongo.name }}
    app.kubernetes.io/component: {{ .Values.mongo.name }}
spec:
  ports:
    - name: mongo
      port: {{ .Values.mongo.service.port }}
      targetPort: {{ .Values.mongo.service.port }}
  selector:
    app: {{ .Values.mongo.name }}
  type: {{ .Values.mongo.service.type }}