apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.flaskapp.name }}
  name: {{ .Values.flaskapp.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.flaskapp.name }}
  strategy: {}
  template:
    metadata:
      labels:
        app: {{ .Values.flaskapp.name }}
    spec:
      containers:
        - name: {{ .Values.flaskapp.name }}
          image: {{ template "flaskapp.image" . }}
          imagePullPolicy: {{ .Values.flaskapp.imagePullPolicy }}
          env:
            - name: FLASK_ENV
              value: {{ .Values.flaskapp.env }}
            - name: MONGO_HOST
              value: {{ .Values.mongo.name }}
            - name: MONGO_PORT
              value: {{ .Values.mongo.service.port | quote }}
            - name: PORT
              value: {{ .Values.flaskapp.service.port | quote }}
            - name: MONGO_USER
              value: root
            - name: MONGO_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mongo.name }}-credentials
                  key: MONGO_INITDB_ROOT_PASSWORD
          ports:
            - containerPort: {{ .Values.flaskapp.service.port }}
              name: http
