apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: todo-flaskapp
  name: todo-flaskapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-flaskapp
  template:
    metadata:
      labels:
        app: todo-flaskapp
    spec:
      containers:
        - env:
            - name: FLASK_ENV
              value: development
            - name: MONGO_HOST
              value: mongo
            - name: MONGO_PORT
              value: "27017"
            - name: MONGO_USER
              value: root
            - name: MONGO_PASS
              valueFrom:
                secretKeyRef:
                  name: mongo-credentials
                  key: MONGO_INITDB_ROOT_PASSWORD
            - name: PORT
              value: "5000"
          image: coolboi567/todo-flaskapp:latest
          imagePullPolicy: Always
          name: flask-app
          ports:
            - containerPort: 5000
          resources: {}
      restartPolicy: Always
status: {}
