nameoverride: ""

mongo:
  name: mongo
  image:
    registry: docker.io
    repository: mvertes/alpine-mongo
    tag: latest
  imagePullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 27017
  root:
    password: cGE4OHcwcmQ=      # in base64

flaskapp:
  name: todo-list
  env: production
  image:
    registry: docker.io
    repository: ashutoshojha5/todo-list
    tag: latest
  imagePullPolicy: Always
  service:
    type: ClusterIP
    port: 5000