nameoverride: ""

mongo:
  name: mongo
  image:
    registry: docker.io
    repository: mongo
    tag: 7.0
  imagePullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 27017
  root:
    password: cGE4OHcwcmQ=      # in base64

flaskapp:
  name: todo-list
  env: production
  image:
    registry: docker.io
    repository: ashutoshojha5/todo-list
    tag: main
  imagePullPolicy: Always
  service:
    type: ClusterIP
    port: 5000

ingress:
  name: "nginx-ingress"
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"

